update PRODUCTS  set UNITS_IN_STOCK = NULL
where UNAVAILABLE = -1;
 

update PRODUCTS  set UNITS_ON_ORDER = NULL
where UNITS_ON_ORDER = 0;


update ORDERS set EMPLOYEE_NUMBER=7
where EMPLOYEE_NUMBER=2;


update ORDERS  set EMPLOYEE_NUMBER=3
where EMPLOYEE_NUMBER =5;

update ORDERS set EMPLOYEE_NUMBER=1
where EMPLOYEE_NUMBER=8;

update PRODUCTS set SUPPLIER_NUMBER= 1 
where PRODUCT_REF in ( select PRODUCT_REF
from PRODUCTS 
where CATEGORY_CODE in (select CATEGORY_CODE
                        from CATEGORIES 
                        where upper(CATEGORY_NAME)='BOISSONS'));


ALTER TABLE ORDERS ADD CONSTRAINT FK_ORDERS_CUSTOMERS 
FOREIGN KEY (CUSTOMER_CODE) REFERENCES CUSTOMERS (CUSTOMER_CODE);

ALTER TABLE ORDERS ADD CONSTRAINT FK_ORDERS_EMPLOYEES  
FOREIGN KEY (EMPLOYEE_NUMBER) REFERENCES EMPLOYEES (EMPLOYEE_NUMBER);

ALTER TABLE ORDER_DETAILS ADD CONSTRAINT FK_ORDER_DETAILS_ORDERS 
FOREIGN KEY (ORDER_NUMBER) REFERENCES ORDERS  (ORDER_NUMBER);

DELETE FROM ORDER_DETAILS
WHERE PRODUCT_REF NOT IN (SELECT PRODUCT_REF FROM PRODUCTS);


ALTER TABLE ORDER_DETAILS ADD CONSTRAINT FK_ORDER_DETAILS_PRODUCTS   
FOREIGN KEY (PRODUCT_REF) REFERENCES PRODUCTS  (PRODUCT_REF);

ALTER TABLE EMPLOYEES  ADD CONSTRAINT FK_EMPLOYEES_EMPLOYES 
FOREIGN KEY (REPORTS_TO) REFERENCES EMPLOYEES (EMPLOYEE_NUMBER);

ALTER TABLE PRODUCTS ADD CONSTRAINT FK_PRODUCTS_CATEGORIE 
FOREIGN KEY (CATEGORY_CODE) REFERENCES CATEGORIES (CATEGORY_CODE);

ALTER TABLE PRODUCTS  ADD CONSTRAINT FK_PRODUCTS_SUPPLIERS  
FOREIGN KEY (SUPPLIER_NUMBER) REFERENCES SUPPLIERS (SUPPLIER_NUMBER);